### ISSUE TITLE
setPreviousPageItem and setNextPageItem return error

### ISSUE THREAD

**Issue by luapascoal** [DevNatan/inventory-framework#187]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐛 Describe the bug

![image](https://user-images.githubusercontent.com/55550262/182979090-c0534837-ce2a-421e-8532-507ab5150193.png)

java.lang.IllegalArgumentException: No item were provided and the rendering function was not defined
ot(...).onRender(...) or a fallback item #slot(fallbackItem)

### ✔️ Expected behavior

did not return any item

### 👣 Steps to Reproduce

just add return in the bifunction it bugs

### 💻 Platform

- [X] Bukkit
- [ ] Sponge
- [ ] Other

### ⭐ Versions

1.8.9

**Comment by luapascoal** [comment]
`java.lang.IllegalArgumentException: No item were provided and the rendering function was not defined at slot 45.You must use a rendering function #slot(...).onRender(...) or a fallback item #slot(fallbackItem)
        at me.saiintbrisson.minecraft.AbstractVirtualView.render(AbstractVirtualView.java:194) ~[?:?]
        at me.saiintbrisson.minecraft.AbstractPaginatedView.renderItemAndApplyOnContext(AbstractPaginatedView.java:301) ~[?:?]
        at me.saiintbrisson.minecraft.AbstractPaginatedView.updateNavigationItem(AbstractPaginatedView.java:628) ~[?:?]
        at me.saiintbrisson.minecraft.AbstractPaginatedView.lambda$updateContext$9(AbstractPaginatedView.java:582) ~[?:?]
        at me.saiintbrisson.minecraft.AbstractPaginatedView.renderLayoutBlocking(AbstractPaginatedView.java:408) ~[?:?]
        at me.saiintbrisson.minecraft.AbstractPaginatedView.tryRenderLayout(AbstractPaginatedView.java:370) ~[?:?]
        at me.saiintbrisson.minecraft.AbstractPaginatedView.updateContext(AbstractPaginatedView.java:581) ~[?:?]
        at me.saiintbrisson.minecraft.AbstractPaginatedView.render(AbstractPaginatedView.java:284) ~[?:?]
        at me.saiintbrisson.minecraft.AbstractView.postOpen(AbstractView.java:281) ~[?:?]
        at me.saiintbrisson.minecraft.AbstractView.open(AbstractView.java:260) ~[?:?]
        at me.saiintbrisson.minecraft.ViewFrame.lambda$open$0(ViewFrame.java:227) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched_1.8.8.jar:git-PaperSpigot-445]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]`

**Comment by DevNatan** [comment]
Fixed in #205
