### ISSUE TITLE
Update job not started to be resumed

### ISSUE THREAD

**Issue by DevNatan** [DevNatan/inventory-framework#216]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐛 Describe the bug

```
java.lang.IllegalStateException: Update job not started to be resumed
        at me.saiintbrisson.minecraft.BukkitViewUpdateJobImpl.resume(BukkitViewUpdateJobImpl.java:60) ~[?:?]
        at me.saiintbrisson.minecraft.pipeline.interceptors.ScheduledUpdateInterceptor$Render.intercept(ScheduledUpdateInterceptor.java:34) ~[?:?]
        at me.saiintbrisson.minecraft.pipeline.interceptors.ScheduledUpdateInterceptor$Render.intercept(ScheduledUpdateInterceptor.java:24) ~[?:?]
        at me.saiintbrisson.minecraft.pipeline.PipelineContext.loop(PipelineContext.java:39) ~[?:?]
        at me.saiintbrisson.minecraft.pipeline.PipelineContext.proceed(PipelineContext.java:49) ~[?:?]
        at me.saiintbrisson.minecraft.pipeline.PipelineContext.execute(PipelineContext.java:55) ~[?:?]
        at me.saiintbrisson.minecraft.pipeline.Pipeline.execute(Pipeline.java:117) ~[?:?]
        at me.saiintbrisson.minecraft.AbstractView.lambda$render$0(AbstractView.java:279) ~[?:?]
        at me.saiintbrisson.minecraft.AbstractVirtualView.runCatching(AbstractVirtualView.java:383) ~[?:?]
        at me.saiintbrisson.minecraft.AbstractView.render(AbstractView.java:277) ~[?:?]
        at me.saiintbrisson.minecraft.pipeline.interceptors.OpenInterceptor.finishOpen(OpenInterceptor.java:72) ~[?:?]
        at me.saiintbrisson.minecraft.pipeline.interceptors.OpenInterceptor.intercept(OpenInterceptor.java:30) ~[?:?]
        at me.saiintbrisson.minecraft.pipeline.interceptors.OpenInterceptor.intercept(OpenInterceptor.java:19) ~[?:?]
        at me.saiintbrisson.minecraft.pipeline.PipelineContext.loop(PipelineContext.java:39) ~[?:?]
        at me.saiintbrisson.minecraft.pipeline.PipelineContext.proceed(PipelineContext.java:49) ~[?:?]
        at me.saiintbrisson.minecraft.pipeline.PipelineContext.execute(PipelineContext.java:55) ~[?:?]
        at me.saiintbrisson.minecraft.pipeline.Pipeline.execute(Pipeline.java:117) ~[?:?]
        at me.saiintbrisson.minecraft.AbstractView.open(AbstractView.java:270) ~[?:?]
        at me.saiintbrisson.minecraft.ViewFrame.lambda$open$0(ViewFrame.java:245) ~[?:?]
```

### 💻 Platform

- [X] Bukkit
- [X] Sponge
- [X] Other

### ⭐ Versions

IF v2.5.4-beta

### ✍️ Additional context

https://github.com/DevNatan/inventory-framework/issues/139#issuecomment-1224990134
```kotlin
class SettingsView(private val uhc: UHC) : View(9 * 6, "§cParamètres") {

    init {
        isCancelOnClick = true
        isCancelOnClone = true
        isCancelOnDrag = true
        isCancelOnDrop = true
        isCancelOnPickup = true
        isCancelOnMoveOut = true
        isCancelOnShiftClick = true

        slot(0, ItemStack(Material.BOOK_AND_QUILL)).onClick {
            it.open(SettingsView::class.java)
        }

        slot(1, ItemStack(Material.FEATHER)).onRender {
            it.setItem(ItemBuilder(Material.FEATHER).displayName("§e${uhc.gameConfiguration.preLoad}").build())
        }.onClick {
            uhc.gameConfiguration.preLoad = !uhc.gameConfiguration.preLoad
            it.update()
        }

        scheduleUpdate(20)
    }
}
```

**Comment by DevNatan** [comment]
@Azodox u can track your issue here ^
