### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by zAlyson** [DevNatan/inventory-framework#242]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐛 Describe the bug

I'm not sure why it happened and how to reproduce it. I just saw the exception in the logs.

```
java.util.ConcurrentModificationException: null
	at java.util.ArrayList.forEach(ArrayList.java:1543) ~[?:?]
	at me.saiintbrisson.minecraft.pipeline.interceptors.OpenInterceptor.finishOpen(OpenInterceptor.java:75) ~[?:?]
	at me.saiintbrisson.minecraft.pipeline.interceptors.OpenInterceptor.intercept(OpenInterceptor.java:30) ~[?:?]
	at me.saiintbrisson.minecraft.pipeline.interceptors.OpenInterceptor.intercept(OpenInterceptor.java:19) ~[?:?]
	at me.saiintbrisson.minecraft.pipeline.PipelineContext.loop(PipelineContext.java:39) ~[?:?]
	at me.saiintbrisson.minecraft.pipeline.PipelineContext.proceed(PipelineContext.java:49) ~[?:?]
	at me.saiintbrisson.minecraft.pipeline.PipelineContext.execute(PipelineContext.java:55) ~[?:?]
	at me.saiintbrisson.minecraft.pipeline.Pipeline.execute(Pipeline.java:116) ~[?:?]
	at me.saiintbrisson.minecraft.AbstractView.open(AbstractView.java:308) ~[?:?]
	at me.saiintbrisson.minecraft.ViewFrame.lambda$open$0(ViewFrame.java:255) ~[?:?]
```

### 💻 Platform

- [X] Bukkit
- [ ] Sponge
- [ ] Other

### ⭐ Versions

 v2.5.4-rc.1 (10-09-2022)

**Comment by zAlyson** [comment]
Have you been working on this issue?
