### ISSUE TITLE
Fallback to platform default ViewType if it's unspecified

### ISSUE THREAD

**Issue by DevNatan** [DevNatan/inventory-framework#313]
```
Caused by: java.lang.NullPointerException: Cannot invoke "me.devnatan.inventoryframework.ViewType.normalize(int)" because the return value of "me.devnatan.inventoryframework.ViewConfig.getType()" is null
        at me.devnatan.inventoryframework.pipeline.OpenInterceptor.createRenderContext(OpenInterceptor.java:74) ~[?:?]
        at me.devnatan.inventoryframework.pipeline.OpenInterceptor.finishOpen(OpenInterceptor.java:58) ~[?:?]
        at me.devnatan.inventoryframework.pipeline.OpenInterceptor.intercept(OpenInterceptor.java:33) ~[?:?]
        at me.devnatan.inventoryframework.pipeline.OpenInterceptor.intercept(OpenInterceptor.java:16) ~[?:?]
```

**Comment by DevNatan** [comment]
Before v3 #278
