### ISSUE TITLE
Version 3.0.10 AnvilGUI not work

### ISSUE THREAD

**Issue by ch4ika** [DevNatan/inventory-framework#667]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐛 Describe the bug

[00:26:37] [Server thread/ERROR]: Error occurred while enabling PrimeTrade v1.0 (Is it up to date?)
java.lang.IllegalArgumentException: Phase CONTEXT_OPEN was not registered for this pipeline
	at me.devnatan.inventoryframework.pipeline.Pipeline.intercept(Pipeline.java:93) ~[PrimeCorePlugin-0.2.1-SNAPSHOT.jar:?]
	at me.devnatan.inventoryframework.AnvilInputFeature.handleOpen(AnvilInputFeature.java:122) ~[PrimeCorePlugin-0.2.1-SNAPSHOT.jar:?]
	at me.devnatan.inventoryframework.AnvilInputFeature.lambda$createFrameworkInterceptor$0(AnvilInputFeature.java:65) ~[PrimeCorePlugin-0.2.1-SNAPSHOT.jar:?]
	at me.devnatan.inventoryframework.pipeline.PipelineContext.loop(PipelineContext.java:43) ~[PrimeCorePlugin-0.2.1-SNAPSHOT.jar:?]
	at me.devnatan.inventoryframework.pipeline.PipelineContext.proceed(PipelineContext.java:53) ~[PrimeCorePlugin-0.2.1-SNAPSHOT.jar:?]
	at me.devnatan.inventoryframework.pipeline.PipelineContext.execute(PipelineContext.java:59) ~[PrimeCorePlugin-0.2.1-SNAPSHOT.jar:?]
	at me.devnatan.inventoryframework.pipeline.Pipeline.execute(Pipeline.java:128) ~[PrimeCorePlugin-0.2.1-SNAPSHOT.jar:?]
	at me.devnatan.inventoryframework.ViewFrame.register(ViewFrame.java:197) ~[PrimeCorePlugin-0.2.1-SNAPSHOT.jar:?]
	at de.primecodes.trade.TradePlugin.onEnable(TradePlugin.java:62) ~[PrimeTrade-1.0-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:190) ~[paper-1.20.2.jar:git-Paper-"931781c"]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.2.jar:git-Paper-"931781c"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:646) ~[paper-1.20.2.jar:git-Paper-"931781c"]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:557) ~[paper-1.20.2.jar:git-Paper-"931781c"]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:627) ~[paper-1.20.2.jar:git-Paper-"931781c"]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:424) ~[paper-1.20.2.jar:git-Paper-"931781c"]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.2.jar:git-Paper-"931781c"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1086) ~[paper-1.20.2.jar:git-Paper-"931781c"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-"931781c"]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]

### 💻 Platform

- [ ] Bukkit
- [ ] Sponge
- [ ] Other

### ⭐ Server Version

1.20.2

### 📚 Library Version

3.0.10

**Comment by nicolube** [comment]
@DevNatan I think u can close this one.

**Comment by nicolube** [comment]
@DevNatan This can still be closed.
