### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by goncalodelima** [DevNatan/inventory-framework#680]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### 🐛 Describe the bug

codigo executado no onFirstRender com size 3: (se retirar de setar o ultimo item no ultimo slot isso n acontece)

    for (ItemStack item : barrel.getItemsLoot()) {
                System.out.println("slot: " + slot + " | " + item.getType());
                render.slot(slot, item);
                slot++;
            }

[11:49:49] [Server thread/INFO]: slot: 0 | CHAINMAIL_CHESTPLATE

[11:49:49] [Server thread/INFO]: slot: 1 | MELON_SEEDS

[11:49:49] [Server thread/INFO]: slot: 2 | GOLD_PICKAXE

[11:49:49] [Server thread/INFO]: slot: 3 | SEEDS

[11:49:49] [Server thread/INFO]: slot: 4 | ENDER_STONE

[11:49:49] [Server thread/INFO]: slot: 5 | ENDER_STONE

[11:49:49] [Server thread/INFO]: slot: 6 | ENDER_STONE

[11:49:49] [Server thread/INFO]: slot: 7 | ENDER_STONE

[11:49:49] [Server thread/INFO]: slot: 8 | ENDER_STONE

[11:49:49] [Server thread/INFO]: slot: 9 | ENDER_STONE

[11:49:49] [Server thread/INFO]: slot: 10 | ENDER_STONE

[11:49:49] [Server thread/INFO]: slot: 11 | ENDER_STONE

[11:49:49] [Server thread/INFO]: slot: 12 | ENDER_STONE

[11:49:49] [Server thread/INFO]: slot: 13 | ENDER_STONE

[11:49:49] [Server thread/INFO]: slot: 14 | ENDER_STONE

[11:49:49] [Server thread/INFO]: slot: 15 | ENDER_STONE

[11:49:49] [Server thread/INFO]: slot: 16 | ENDER_STONE

[11:49:49] [Server thread/INFO]: slot: 17 | ENDER_STONE

[11:49:49] [Server thread/INFO]: slot: 18 | ENDER_STONE

[11:49:49] [Server thread/INFO]: slot: 19 | ENDER_STONE

[11:49:49] [Server thread/INFO]: slot: 20 | ENDER_STONE

[11:49:49] [Server thread/INFO]: slot: 21 | ENDER_STONE

[11:49:49] [Server thread/INFO]: slot: 22 | ENDER_STONE

[11:49:49] [Server thread/INFO]: slot: 23 | ENDER_STONE

[11:49:49] [Server thread/INFO]: slot: 24 | ENDER_STONE

[11:49:49] [Server thread/INFO]: slot: 25 | ENDER_STONE

[11:49:49] [Server thread/INFO]: slot: 26 | ENDER_STONE

[11:49:49] [Server thread/WARN]: [twins-core] Task #428 for twins-core v1.0.0 generated an exception
java.lang.ArrayIndexOutOfBoundsException: Index 27 out of bounds for length 27
	at org.bukkit.craftbukkit.v1_8_R3.inventory.CraftInventoryCustom$MinecraftInventory.getItem(CraftInventoryCustom.java:71) ~[FlamePaper.jar:git-PaperSpigot-cbe632ca]
	at org.bukkit.craftbukkit.v1_8_R3.inventory.CraftInventory.getItem(CraftInventory.java:47) ~[FlamePaper.jar:git-PaperSpigot-cbe632ca]
	at me.devnatan.inventoryframework.BukkitViewContainer.hasItem(BukkitViewContainer.java:111) ~[?:?]
	at me.devnatan.inventoryframework.pipeline.AvailableSlotInterceptor.isSlotNotAvailableForAutoFilling(AvailableSlotInterceptor.java:121) ~[?:?]
	at me.devnatan.inventoryframework.pipeline.AvailableSlotInterceptor.resolveFromInitialSlot(AvailableSlotInterceptor.java:46) ~[?:?]
	at me.devnatan.inventoryframework.pipeline.AvailableSlotInterceptor.intercept(AvailableSlotInterceptor.java:26) ~[?:?]
	at me.devnatan.inventoryframework.pipeline.AvailableSlotInterceptor.intercept(AvailableSlotInterceptor.java:16) ~[?:?]
	at me.devnatan.inventoryframework.pipeline.PipelineContext.loop(PipelineContext.java:43) ~[?:?]
	at me.devnatan.inventoryframework.pipeline.PipelineContext.proceed(PipelineContext.java:53) ~[?:?]
	at me.devnatan.inventoryframework.pipeline.PipelineContext.execute(PipelineContext.java:59) ~[?:?]
	at me.devnatan.inventoryframework.pipeline.Pipeline.execute(Pipeline.java:112) ~[?:?]
	at me.devnatan.inventoryframework.PlatformView.renderContext(PlatformView.java:321) ~[?:?]
	at me.devnatan.inventoryframework.pipeline.PlatformOpenInterceptor.finishOpen(PlatformOpenInterceptor.java:54) ~[?:?]
	at me.devnatan.inventoryframework.pipeline.PlatformOpenInterceptor.intercept(PlatformOpenInterceptor.java:28) ~[?:?]
	at me.devnatan.inventoryframework.pipeline.PlatformOpenInterceptor.intercept(PlatformOpenInterceptor.java:12) ~[?:?]
	at me.devnatan.inventoryframework.pipeline.PipelineContext.loop(PipelineContext.java:43) ~[?:?]
	at me.devnatan.inventoryframework.pipeline.PipelineContext.proceed(PipelineContext.java:53) ~[?:?]
	at me.devnatan.inventoryframework.pipeline.PipelineContext.execute(PipelineContext.java:59) ~[?:?]
	at me.devnatan.inventoryframework.pipeline.Pipeline.execute(Pipeline.java:119) ~[?:?]
	at me.devnatan.inventoryframework.PlatformView.open(PlatformView.java:103) ~[?:?]
	at me.devnatan.inventoryframework.PlatformView.navigateTo(PlatformView.java:161) ~[?:?]
	at me.devnatan.inventoryframework.context.PlatformConfinedContext.openForPlayer(PlatformConfinedContext.java:36) ~[?:?]
	at me.devnatan.inventoryframework.context.PlatformConfinedContext.openForPlayer(PlatformConfinedContext.java:29) ~[?:?]
	at me.devnatan.inventoryframework.context.PlatformRenderContext.openForPlayer(PlatformRenderContext.java:296) ~[?:?]
	at com.twins.core.barrel.inventory.OpenBarrelInventory.lambda$onFirstRender$5(OpenBarrelInventory.java:153) ~[?:?]
	at me.devnatan.inventoryframework.component.BukkitItemComponentBuilder.lambda$renderWith$0(BukkitItemComponentBuilder.java:146) ~[?:?]
	at me.devnatan.inventoryframework.component.ItemComponent.render(ItemComponent.java:140) ~[?:?]
	at me.devnatan.inventoryframework.context.AbstractIFContext.renderComponent(AbstractIFContext.java:132) ~[?:?]
	at me.devnatan.inventoryframework.context.PlatformContext.renderComponent(PlatformContext.java:7) ~[?:?]
	at me.devnatan.inventoryframework.component.ItemComponent.updated(ItemComponent.java:188) ~[?:?]
	at me.devnatan.inventoryframework.context.AbstractIFContext.updateComponent(AbstractIFContext.java:169) ~[?:?]
	at me.devnatan.inventoryframework.context.PlatformContext.updateComponent(PlatformContext.java:7) ~[?:?]
	at me.devnatan.inventoryframework.pipeline.UpdateInterceptor.intercept(UpdateInterceptor.java:21) ~[?:?]
	at me.devnatan.inventoryframework.pipeline.UpdateInterceptor.intercept(UpdateInterceptor.java:11) ~[?:?]
	at me.devnatan.inventoryframework.pipeline.PipelineContext.loop(PipelineContext.java:43) ~[?:?]
	at me.devnatan.inventoryframework.pipeline.PipelineContext.proceed(PipelineContext.java:53) ~[?:?]
	at me.devnatan.inventoryframework.pipeline.PipelineContext.execute(PipelineContext.java:59) ~[?:?]
	at me.devnatan.inventoryframework.pipeline.Pipeline.execute(Pipeline.java:119) ~[?:?]
	at me.devnatan.inventoryframework.context.AbstractIFContext.update(AbstractIFContext.java:189) ~[?:?]
	at me.devnatan.inventoryframework.context.PlatformContext.update(PlatformContext.java:7) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:194) ~[?:?]
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1715) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:556) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:546) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:611) ~[?:?]
	at me.devnatan.inventoryframework.pipeline.ScheduledUpdateAfterRenderInterceptor.lambda$intercept$0(ScheduledUpdateAfterRenderInterceptor.java:25) ~[?:?]
	at me.devnatan.inventoryframework.internal.BukkitTaskJobImpl.loop(BukkitTaskJobImpl.java:39) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[FlamePaper.jar:git-PaperSpigot-cbe632ca]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) ~[FlamePaper.jar:git-PaperSpigot-cbe632ca]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:920) ~[FlamePaper.jar:git-PaperSpigot-cbe632ca]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:368) ~[FlamePaper.jar:git-PaperSpigot-cbe632ca]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:846) ~[FlamePaper.jar:git-PaperSpigot-cbe632ca]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:682) ~[FlamePaper.jar:git-PaperSpigot-cbe632ca]
	at net.minecraft.server.v1_8_R3.MinecraftServer.lambda$spin$0(MinecraftServer.java:135) ~[FlamePaper.jar:git-PaperSpigot-cbe632ca]
	at java.lang.Thread.run(Thread.java:1570) ~[?:?]

### 💻 Platform

- [X] Bukkit
- [ ] Sponge
- [ ] Other

### ⭐ Server Version

1.8.8

### 📚 Library Version

3.0.8

**Comment by 2lay** [comment]
Hey! I am also experiencing this issue. I can't set anything in the 27th slot, either using the ``render.slot`` or ``render.lastSlot`` method.  I am on PaperSpigot 1.21.1 and 3.0.11 version of the plugin.

**Comment by nicolube** [comment]
@goncalodelima Same thing indexing start at 0, the slot 27 is index 26... so index 27 will be out of inv...

**Comment by DevNatan** [comment]
@goncalodelima I'm not being able to reproduce. Both `slot(26, [...])` and `lastSlot([...])` with `config.size(3)` or `config.size(27)` on container config works fine.

onRender's context `slot(x)` is index-based so I recommend you to check container size before adding it otherwise it will throw an exception. You can use `render.getContainer()` to access container settings.

**Comment by goncalodelima** [comment]
Se eu apenas setar um item no ultimo slot com render.slot tambem nao ocorre a exception, mas caso eu percorra todos os slots do inventario (incluindo o ultimo) já ocorre a exception.
